FROM node:18-alpine

#Create router directory
WORKDIR /router

#Install app dependencies
COPY listings*.json ./

#Run npm install
RUN npm install

#Bundles app source
COPY . . 

EXPOSE 3000

CMD [ "listings.js", "users.js", "server.js", "filters.js" ]

